dist: xenial
services:
  - docker
language: python
python:
  - "3.7"
install:
  - docker-compose -f local.yml build
  - docker-compose -f local.yml run --rm django python manage.py migrate
  - docker-compose -f local.yml up -d
  - sleep 12
script:
  - docker-compose -f local.yml run django pytest
